pipeline:
  publish:
    image: ribase/drone-s3-sync
    acl: public-read
    region: "eu-west-1"
    bucket: "factorio-admin"
    access_key: $$ACCESS
    secret_key: $$SECRET
    source: /drone/src/github.com/ribase/factorio-admin/
    target: /
    recursive: true
    when:
      branch: master